# Generated by Django 3.0.4 on 2020-04-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200419_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(help_text='Wybierz kategorię wpisu', to='blog.Category', verbose_name='Kategoria'),
        ),
    ]
